version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pass123
    networks:
      - my-network

networks:
  my-network:
