version: "3"
services:
  app:
    build:
      context: .
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: demo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
