spring:
  datasource:
    url: jdbc:postgresql://db:5432/demo_db
    username: user123
    password: pass123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
