spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo_db}
    username: ${SPRING_DATASOURCE_USERNAME:user123}
    password: ${SPRING_DATASOURCE_PASSWORD:pass123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
