spring:
  datasource:
    url: jdbc:postgresql://ep-calm-dawn-417319.ap-southeast-1.aws.neon.tech:5432/testdatabase
    username: fl0user
    password: OczoAU61RuKy
  jpa:
    hibernate:
      ddl-auto: update
